from .advanced_quantum_walk import AdvancedQuantumWalk
from .entangled_quantum_walk import EntangledQuantumWalk
from .multidimensional_quantum_walk import MultiDimensionalQuantumWalk
from quantum_ml import QuantumSimulator, QMLInterface
from .quantum_walk_gui import QuantumWalkGUI
from quantum_walk_network import QuantumWalkOnNetwork, IntegratedQuantumWalk
from .quantum_walk import QuantumWalk
#from visualizations #no classes yet